- name: black
  version: 24.2.0
- name: flake8
  version: 3.7.9
- name: flake8-bugbear
  version: 24.2.6
- name: flake8-comprehensions
  version: 3.14.0
- name: Flask
  version: 1.1.2
- name: future
  version: 0.18.2
- name: fvcore
  version: 0.1.5.post20221221
- name: gitdb
  version: 4.0.11
- name: GitPython
  version: 3.1.41
- name: grpcio
  version: 1.37.0
- name: h5py
  version: 3.2.1
- name: imageio
  version: 2.9.0
- name: imagesize
  version: 1.2.0
- name: iopath
  version: 0.1.10
- name: ipdb
  version: 0.13.7
- name: json5
  version: 0.9.5
- name: jsonschema
  version: "@"
- name: jupyter-client
  version: 6.1.12
- name: jupyter-core
  version: 4.7.1
- name: jupyter-tensorboard
  version: @
- name: jupyterlab
  version: 2.3.1
- name: jupyterlab-pygments
  version: 0.1.2
- name: jupyterlab-server
  version: 1.2.0
- name: jupytext
  version: 1.11.1
- name: kiwisolver
  version: 1.3.1
- name: matplotlib
  version: 3.4.1
- name: numpy
  version: "@"
- name: nvidia-dali-cuda110
  version: 1.0.0
- name: nvidia-dlprof-pytorch-nvtx
  version: "@"
- name: nvidia-pyprof
  version: "@"
- name: nvidia-tensorboard
  version: "@"
- name: nvidia-tensorboard-plugin-dlprof
  version: "@"
- name: onnx
  version: "@"
- name: onnxruntime
  version: 1.7.0
- name: opencv-python-headless
  version: 4.9.0.80
- name: pandas
  version: 1.1.4
- name: pandocfilters
  version: 1.4.3
- name: parso
  version: "@"
- name: pathspec
  version: 0.12.1
- name: pathvalidate
  version: 2.4.1
- name: pexpect
  version: "@"
- name: pickleshare
  version: "@"
- name: pillow
  version: 10.2.0
- name: pkginfo
  version: 1.7.0
- name: platformdirs
  version: 4.2.0
- name: plotly
  version: 5.19.0
- name: pluggy
  version: 0.13.1
- name: polygraphy
  version: 0.28.3
- name: pooch
  version: 1.3.0
- name: portalocker
  version: 2.8.2
- name: preshed
  version: 3.0.2
- name: prettytable
  version: 2.1.0
- name: progressbar
  version: 2.5
- name: prometheus-client
  version: 0.10.1
- name: prompt-toolkit
  version: "@"
- name: protobuf
  version: 3.15.8
- name: psutil
  version: "@"
- name: ptyprocess
  version: "@"
- name: py
  version: 1.10.0
- name: pybind11
  version: 2.6.2
- name: pycocotools
  version: "@"
- name: pycodestyle
  version: 2.5.0
- name: pycosat
  version: 0.6.3
- name: pycparser
  version: "@"
- name: pycuda
  version: 2020.1
- name: pydicom
  version: 2.4.4
- name: pydot
  version: 1.4.2
- name: pyflakes
  version: 2.1.1
- name: pygments
  version: 2.17.2
- name: pynvml
  version: 8.0.4
- name: pyOpenSSL
  version: "@"
- name: pyparsing
  version: 2.4.7
- name: pyrsistent
  version: "@"
- name: PySocks
  version: "@"
- name: pytablewriter
  version: 0.47.0
- name: pytest
  version: 6.2.3
- name: pytest-cov
  version: 2.11.1
- name: pytest-pythonpath
  version: 0.7.3
- name: python-dateutil
  version: 2.8.1
- name: python-hostlist
  version: 1.21
- name: python-nvd3
  version: 0.15.0
- name: python-slugify
  version: 4.0.1
- name: pytools
  version: 2021.2.3
- name: pytorch-quantization
  version: 2.1.0
- name: pytorch-transformers
  version: 1.1.0
- name: pytorch3d
  version: 0.7.2
- name: scikit-image
  version: 0.15.0
- name: scikit-learn
  version: 0.24.1
- name: scipy
  version: "@"
- name: tensorboard
  version: "@"
- name: torch
  version: 1.11.0+cu113
- name: torchaudio
  version: 0.11.0+cu113
- name: torchio
  version: 0.19.5
- name: torchtext
  version: "@"
- name: torchvision
  version: 0.12.0+cu113
- name: tornado
  version: 6.1
- name: tqdm
  version: 4.53.0
- name: usort
  version: 1.0.8.post1
- name: wandb
  version: 0.16.3
